/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lucene.toy.app;

import org.apache.lucene.document.*;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.store.FSDirectory;
import org.apache.tika.Tika;
import org.apache.tika.metadata.Metadata;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Objects;
import java.util.stream.Stream;

public class App {
    public static void main(String[] args) throws IOException {
        FSDirectory d = FSDirectory.open(Paths.get("/tmp/lucene-toy"));
        IndexWriterConfig config = new IndexWriterConfig();

        IndexWriter writer = new IndexWriter(d, config);

        books().forEach(doc -> {
            try {
                writer.addDocument(doc);
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
        writer.close();
    }

    private static Stream<Document> books() throws IOException {
        Tika tika = new Tika();
        Stream<Path> paths = Files.list(Paths.get("/Users/george/books/pdf"));
        return paths.map(path -> {
            try {
                Metadata metadata = new Metadata();
                Reader r = tika.parse(path, metadata);
                String name = metadata.get("resourceName");
                String length = metadata.get("Content-Length");
                String type = metadata.get("Content-Type");
                Document doc = new Document();
                doc.add(new TextField("title", name, Field.Store.YES));
                doc.add(new LongPoint("length", Long.parseLong(length)));
                doc.add(new StringField("type", type, Field.Store.YES));
                return doc;
            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }).filter(Objects::nonNull);
    }

    private static Document doc() {
        Document doc = new Document();
        doc.add(new TextField("title", "The Book of Why", Field.Store.YES));
        doc.add(new FloatPoint("price", 29.9f));
        doc.add(new StringField("author", "", Field.Store.YES));
        doc.add(new StringField("author", "", Field.Store.YES));
        doc.add(new StringField("author", "", Field.Store.YES));
        return doc;
    }
}
